### ISSUE TITLE
[kvm-qemu.sh] - libvirtd fails to start because apparmor fails to start, due to unsupported Invalid capability in profiles. 

### ISSUE THREAD

**Issue by zoomequipd** [doomedraven/Tools#100] opened 2021-08-31 23:32 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X] I read my log of instalation, all issues will be closed if you don't do your part of work
- [X] I understand that reporting issue related to any instalation script without instalation log is useless and will be closed

# Expected Behavior

libvirtd starts without error after running kvm-qemu.sh and rebooting

# Current Behavior

libvirtd fails to start due to apparmor error, apparmor fails to start due to an invalid capability

# Failure Information (for bugs)

libvirtd status
```
● libvirtd.service - Virtualization daemon
     Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
     Active: failed (Result: start-limit-hit) since Tue 2021-08-31 17:54:53 CDT; 37min ago
TriggeredBy: ● libvirtd-ro.socket
             ● libvirtd-admin.socket
             ● libvirtd.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
    Process: 11468 ExecStart=/usr/sbin/libvirtd $LIBVIRTD_ARGS (code=exited, status=0/SUCCESS)
   Main PID: 11468 (code=exited, status=0/SUCCESS)
      Tasks: 2 (limit: 32768)
     Memory: 25.3M
     CGroup: /system.slice/libvirtd.service
             ├─1609 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
             └─1610 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper

Aug 31 17:54:53 cents-cape libvirtd[11468]: libvirt version: 7.6.0
Aug 31 17:54:53 cents-cape libvirtd[11468]: hostname: cents-cape
Aug 31 17:54:53 cents-cape libvirtd[11468]: unsupported configuration: Security driver apparmor not enabled
Aug 31 17:54:53 cents-cape libvirtd[11468]: internal error: Failed to initialize security drivers
Aug 31 17:54:53 cents-cape libvirtd[11468]: Initialization of QEMU state driver failed: internal error: Failed to initialize security drivers
Aug 31 17:54:53 cents-cape libvirtd[11468]: Driver state initialization failed
```

apparmor status
```
● apparmor.service - Load AppArmor profiles
     Loaded: loaded (/lib/systemd/system/apparmor.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-08-30 21:03:18 CDT; 21h ago
       Docs: man:apparmor(7)
             https://gitlab.com/apparmor/apparmor/wikis/home/
   Main PID: 778 (code=exited, status=1/FAILURE)

Aug 30 21:03:16 cents-cape apparmor.systemd[808]: AppArmor parser error for /etc/apparmor.d in /etc/apparmor.d/usr.sbin.libvirtd at line 29: Invalid capability bpf.
Aug 30 21:03:16 cents-cape apparmor.systemd[812]: AppArmor parser error for /etc/apparmor.d in /etc/apparmor.d/usr.sbin.virtqemud at line 29: Invalid capability bpf.
```
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Fresh Install of ubuntu 20.04
2. run `sudo ./kvm-qemu.sh all cape | tee kvm-qemu.log`
3. reboot
4. run `sudo systemctl status libvirtd`
5. observe error

## Context

Removing line 29 from both `/etc/apparmor.d/usr.sbin.libvirtd` and `/etc/apparmor.d/usr.sbin.virtqemud` resulted in it throwing another error
```
Aug 31 18:47:49 cents-cape apparmor.systemd[13476]: AppArmor parser error for /etc/apparmor.d in /etc/apparmor.d/usr.sbin.libvirtd at line 29: Invalid capability perfmon.
Aug 31 18:47:49 cents-cape apparmor.systemd[13480]: AppArmor parser error for /etc/apparmor.d in /etc/apparmor.d/usr.sbin.virtqemud at line 29: Invalid capability perfmon.
```

Again, removed that line and then appamor started correctly and allowed libvirtd to start normally.

Might be related to this thread on the libvirt mailing list - https://www.mail-archive.com/libvir-list@redhat.com/msg218313.html

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04.3 LTS
| Software version | QEMU 6.1.0, virsh 7.6.0

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by zoomequipd** [comment] 2021-08-31 23:52
I accidentally submitted this issue before completing it (hence the updates to the above message).  I'm not sure if this is actually a problem that should be solved within this project.  Feel free to close as needed, if nothing else perhaps another user with the same problem might find the "Context" section useful.

**Comment by zoomequipd** [comment] 2021-08-31 23:54
## Workaround 
Remove the following lines from `/etc/apparmor.d/usr.sbin.libvirtd` and `/etc/apparmor.d/usr.sbin.virtqemud`
```
capability bpf,
capability perfmon,
```

**Comment by zoomequipd** [comment] 2021-09-01 00:13
commit to libvirt which introduced the two allowed capabilities
https://gitlab.com/libvirt/libvirt/-/commit/4f2811eb816ed1da215b86778dfcf483917666a1

this bug report mentions that `perfmon` and `bpf` were added to AppArmor 2.13
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979964

installed on ubuntu 20.04.3 LTS is 
```

**Comment by doomedraven** [comment] 2021-09-01 10:44
Hello, this is interesting, thank you for reporting this, apparmor gives me a lot of headache from time to time. i will keep this open as i would like to get this working without removing features from the config, but right now don't have so much spare time, maybe on the weekend

**Comment by doomedraven** [comment] 2021-09-01 20:58
ok i have installed `linux-generic-hwe-20.04`, i was on kernel `5.4`, now im on `5.11` and im getting this error too

**Comment by ditekshen** [comment] 2021-09-10 13:21
I have been troubleshooting this for a while in CAHI. I found that ```apparmor``` version ```2.13.6``` successfully recognizes both ```capability bpf``` and ```capability perfmon```. Do not attempt to install ```apparmor``` version ```3.X```, it introduces more errors.

```bash
$ wget https://launchpad.net/apparmor/2.13/2.13.6/+download/apparmor-2.13.6.tar.gz
$ tar xf apparmor-2.13.6.tar.gz
$ sudo apt-get install swig
$ export PYTHON=/usr/bin/python3
$ export PYTHON_VERSION=3
$ export PYTHON_VERSIONS=python3
$ cd apparmor-2.13.6/
$ cd libraries/libapparmor/
$ ./autogen.sh
$ ./configure --prefix=/usr --with-perl --with-python
$ make
$ sudo make install
$ cd ../../binutils/
$ make
$ sudo make install
$ cd ../parser/
$ make
$ sudo make install
$ cd ../utils/
$ make
$ sudo make install
$ cd ../profiles/
$ make
$ sudo make install
$ sudo ldconfig


$ sudo aa-complain /etc/apparmor.d/usr.sbin.libvirtd
Setting /etc/apparmor.d/usr.sbin.libvirtd to complain mode.

$ sudo aa-complain /etc/apparmor.d/usr.sbin.virtqemud
Setting /etc/apparmor.d/usr.sbin.virtqemud to complain mode.
```

**Comment by doomedraven** [comment] 2021-09-10 13:25
oh nice @ditekshen is what i though that we will need to move to latest/newer apparmor, i will add that to script, but with checkinstall for easier upgrade/cleanup

**Comment by doomedraven** [comment] 2021-09-12 13:30
so we just need new parsers, but the problem is that if apparmor already install there is option build against installed, but it tries to overwrite existent file, checkinstall leaves `deb` backup, and can use that `apt-get -y -o Dpkg::Options::="--force-overwrite"` but i will add that later

**Comment by doomedraven** [comment] 2021-09-12 14:12
ok do you want to try guys ? https://github.com/doomedraven/Tools/commit/26fa7ee26fb7447d2796f2575174a4cc72e11a49
i didn't link it yet to libvirt install, but it worked for me, so few more confirmations would be good

**Comment by ditekshen** [comment] 2021-09-17 06:55
Thanks @doomedraven, works for me. I tested without even building libapparmor:

```bash
function install_apparmor() {
    # Kudos to @ditekshen for the apparmor solution with latest libvirt
    # https://gitlab.com/apparmor/apparmor/-/releases
    APPARMOR_VERSION="2.13.6"
    wget "https://launchpad.net/apparmor/2.13/$APPARMOR_VERSION/+download/apparmor-$APPARMOR_VERSION.tar.gz"
    tar xf "apparmor-$APPARMOR_VERSION.tar.gz"
    sudo apt-get install swig
    export PYTHON=/usr/bin/python3
    export PYTHON_VERSION=3
    export PYTHON_VERSIONS=python3

    cd "apparmor-$APPARMOR_VERSION/parser/"

    USE_SYSTEM=1 make -j"$(nproc)"
    USE_SYSTEM=1 checkinstall -D --pkgname=apparmor-parser --default --install=no

    apt-get -y -o Dpkg::Options::="--force-overwrite" install ./apparmor-parser_*_amd64.deb

    sudo ldconfig
}
```

**Comment by doomedraven** [comment] 2021-09-17 11:58
Thanks for testing and feedback will add that to libvirt after pto

**Comment by zoomequipd** [comment] 2021-09-18 17:19
# Testing Steps
my steps to reproduce were - 
1) fresh install
2) run `sudo bash ./kvm-qemu.sh all cape | tee kvm-qemu.log`
3) reboot
4) run  `sudo ./kvm-qemu.sh apparmor | tee apparmor.log`
5) reboot
6) check apparmor status. 

# Outcome
AppAmror still failed to start

```
zoomequipd@cape-dev:~$ sudo systemctl status apparmor.service 
[sudo] password for zoomequipd: 
● apparmor.service - Load AppArmor profiles
     Loaded: loaded (/lib/systemd/system/apparmor.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2021-09-18 01:03:18 CDT; 7min ago
       Docs: man:apparmor(7)
             https://gitlab.com/apparmor/apparmor/wikis/home/
   Main PID: 697 (code=exited, status=1/FAILURE)

Sep 18 01:03:18 cape-dev apparmor.systemd[763]: Skipping profile in /etc/apparmor.d/disable: usr.bin.firefox
Sep 18 01:03:18 cape-dev apparmor.systemd[772]: AppArmor parser error for /etc/apparmor.d in /etc/apparmor.d/usr.sbin.virtqemud at line 29: Invalid capability bpf.
Sep 18 01:03:18 cape-dev apparmor.systemd[845]: Skipping profile in /etc/apparmor.d/disable: usr.bin.firefox
Sep 18 01:03:18 cape-dev apparmor.systemd[921]: AppArmor parser error for /etc/apparmor.d/usr.sbin.libvirtd in /etc/apparmor.d/usr.sbin.libvirtd at line 29: Invalid capability bpf.
Sep 18 01:03:18 cape-dev apparmor.systemd[928]: Skipping profile in /etc/apparmor.d/disable: usr.sbin.rsyslogd
Sep 18 01:03:18 cape-dev apparmor.systemd[938]: AppArmor parser error for /etc/apparmor.d/usr.sbin.virtqemud in /etc/apparmor.d/usr.sbin.virtqemud at line 29: Invalid capability bpf.
Sep 18 01:03:18 cape-dev apparmor.systemd[697]: Error: At least one profile failed to load
Sep 18 01:03:18 cape-dev systemd[1]: apparmor.service: Main process exited, code=exited, status=1/FAILURE
Sep 18 01:03:18 cape-dev systemd[1]: apparmor.service: Failed with result 'exit-code'.
Sep 18 01:03:18 cape-dev systemd[1]: Failed to start Load AppArmor profiles.
```
# Analysis and Other Minor Issues
## Prompt During Install
got a prompt during the install on the swig install, might just be able to throw a `-y` in there. 
`sudo apt-get install swig` --> `sudo apt-get -y install swig`

## AppArmor log
I find only a single error that might be related within the apparmor log
```
./kvm-qemu.sh: line 237: cd: ../parser/: No such file or directory
```
### Analysis
line 228-237 reads 
```
    cd "apparmor-$APPARMOR_VERSION/libraries/libapparmor/"
    ./autogen.sh
    ./configure --prefix=/usr --with-perl --with-python

    # make -j"$(nproc)"
    # checkinstall -D --pkgname="libapparmor-$APPARMOR_VERSION" --default
    # cd ../../binutils/
    # #make -j"$(nproc)"
    # #checkinstall -D --pkgname=binutils --default
    cd ../parser/
```
line 228 places the working path as `apparmor-2.13.6/libraries/libapparmor/` and line 237 moves up a single directory looking for parser within `apparmor-2.13.6/libraries/parser/` however it should be `apparmor-2.13.6/parser/`

### Proposed Fix
Attempted fix by replacing 237 with `cd ../../parser/` - seems to have resolved the issue. 

### Proposed Fix Testing
Repeated the testing as described above with the two minor fixes - and apparmor now starts

```
zoomequipd@cape-dev:~$ sudo systemctl status apparmor
[sudo] password for zoomequipd: 
● apparmor.service - Load AppArmor profiles
     Loaded: loaded (/lib/systemd/system/apparmor.service; enabled; vendor preset: enabled)
     Active: active (exited) since Sat 2021-09-18 12:14:54 CDT; 4min 24s ago
       Docs: man:apparmor(7)
             https://gitlab.com/apparmor/apparmor/wikis/home/
    Process: 695 ExecStart=/lib/apparmor/apparmor.systemd reload (code=exited, status=0/SUCCESS)
   Main PID: 695 (code=exited, status=0/SUCCESS)

Sep 18 12:14:53 cape-dev systemd[1]: Starting Load AppArmor profiles...
Sep 18 12:14:53 cape-dev apparmor.systemd[695]: Restarting AppArmor
Sep 18 12:14:53 cape-dev apparmor.systemd[695]: Reloading AppArmor profiles
Sep 18 12:14:54 cape-dev apparmor.systemd[695]: Skipped: /etc/apparmor.d/usr.bin.firefox
Sep 18 12:14:54 cape-dev apparmor.systemd[695]: Skipped: /etc/apparmor.d/usr.sbin.rsyslogd
Sep 18 12:14:54 cape-dev systemd[1]: Finished Load AppArmor profiles.
```
I'll make a quick PR on these two minor fixes.

**Comment by doomedraven** [comment] 2021-09-19 08:44
@zoomequipd thank you, im gonna submit the part where apparmor parsers will be installed in libvirt so we can forget about this issue, thank you also @ditekshen to find how easy fix this

**Closed by doomedraven** 2021-09-19 08:44 UTC
