### ISSUE TITLE
Creating VM's using virt-manager after running the script is not possible

### ISSUE THREAD

**Issue by anykeypress** [doomedraven/Tools#76] opened 2021-02-19 20:58 UTC
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I read my log of installation, all issues will be closed if you don't do your part of work

# Expected Behavior
After executing the kvm-qemu.sh script, creating a Virtual Machine using the virt-manager GUI should work as normal

# Current Behavior
When creating a virtual machine, everything works as normal until the machine is to be created. Then an error is thrown as shown in the log / error message below.

# Failure Information (for bugs)
Unable to complete install: 'internal error: process exited while connecting to monitor: /usr/bin/qemu-system-x86_64: error while loading shared libraries: libjemalloc.so.2: cannot open shared object file: No such file or directory'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2001, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 701, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 649, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/local/lib/python3.8/dist-packages/libvirt.py", line 4366, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: internal error: process exited while connecting to monitor: /usr/bin/qemu-system-x86_64: error while loading shared libraries: libjemalloc.so.2: cannot open shared object file: No such file or directory

![image](https://user-images.githubusercontent.com/16607225/108559838-27ccf280-72fc-11eb-9999-0be75b351d37.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Ubuntu 20.04
2. Run the script kvm-qemu.sh
3. The script appears to run normally
4. Attempt to create a virtual machine, the error shown in the screen shot is shown. Virtual machine cannot be created.

## Context
If installing the KVM packages normally (i.e. without any customization as provided by the script, everyhting works fine)
The error occurs regardless if the VHD (qcow2) is present beforehand or created "on the fly".
KVM / QEMU was not present on the system prior to executing the script.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04
| Software version | n/a

## Failure Logs
[kvm-qemu-install.zip](https://github.com/doomedraven/Tools/files/6012901/kvm-qemu-install.zip)

**Comment by doomedraven** [comment] 2021-02-19 21:18
thanks i will try to check this when i will have some time, this is the fun of depend of 3rd part libraries that changes frequently

**Comment by doomedraven** [comment] 2021-02-19 21:19
did you try this? https://github.com/jemalloc/jemalloc/issues/1327

**Comment by anykeypress** [comment] 2021-02-19 21:44
@doomedraven , your the man. That seems to have fixed it. Installing to test to the end now.... cheers

**Comment by doomedraven** [comment] 2021-02-20 06:41
ok without doing any changes it installs fine it here, check if you have this

```
 locate libjemalloc
/usr/local/lib/libjemalloc.so.2
```

**Comment by anykeypress** [comment] 2021-02-20 11:56
Hi @doomedraven , yes I do have that lib.... but only after installing the "patch" that you suggested...

**Comment by doomedraven** [comment] 2021-02-20 13:08
Weird,but thanks for headups

**Comment by doomedraven** [comment] 2021-02-21 14:06
closing this as can't reproduce, and you solved it, next time please also provide the log of the installation if no issue will be invalid, as if something fail and user not check log he should fix it itself ;)

**Closed by doomedraven** 2021-02-21 14:06 UTC

**Comment by anykeypress** [comment] 2021-02-22 07:23
@doomedraven , wasn't the log I provided correct? If not please let me know which one would help, unless you want to keep the issue closed...

**Comment by doomedraven** [comment] 2021-02-22 07:33
that is error msg, that is required, but that isn't log from my script that installs jemalloc aka when you run kvm-qemu.sh

**Comment by anykeypress** [comment] 2021-02-22 07:35
Your log is probably still on the machine, I haven't removed anything, could you point me in the right direction? (i.e. let me know where the log is/was stored) and I will have another look...

**Comment by doomedraven** [comment] 2021-02-22 07:40
It not autocreated, you should run script as - - help says with tee command

**Comment by anykeypress** [comment] 2021-02-22 08:19
@doomedraven , sorry... would you like me to run it again on a vm?

**Comment by doomedraven** [comment] 2021-02-22 08:21
np, you learning. nah i tried to reproduce it on my dev vm restoring snapshot and it didn't fail so meh don't waste time on this
